### ISSUE TITLE
Stackage LTS-7.0

### ISSUE THREAD

**Issue by wictory** [dsorokin/aivika-experiment-chart#1]
Hi!

The [dependency constraint](https://github.com/dsorokin/aivika-experiment-chart/blob/master/aivika-experiment-chart.cabal#L136) for `data-default-class` prevents aivika-experiment-chart from compiling when using stackage LTS-7.0.

**Comment by dsorokin** [comment]
Thanks! Fixed and uploaded to Hackage DB.
